/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  corePlugins: {
    preflight: false,
  },
  important: '#root',
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "on-secondary-container": "#fff7e6",
        "primary-fixed": "#00e3fd",
        "surface-bright": "#2c2c2c",
        "tertiary-dim": "#8d96f4",
        "inverse-on-surface": "#565555",
        "inverse-primary": "#006976",
        "secondary": "#ffd709",
        "error-container": "#9f0519",
        "primary-dim": "#00d4ec",
        "on-background": "#ffffff",
        "primary-fixed-dim": "#00d4ec",
        "tertiary": "#a2aaff",
        "surface-dim": "#0e0e0e",
        "surface-container-lowest": "#000000",
        "surface-container-highest": "#262626",
        "surface-container-low": "#131313",
        "on-secondary-fixed-variant": "#665500",
        "tertiary-fixed": "#a2aaff",
        "on-secondary": "#5b4b00",
        "tertiary-fixed-dim": "#929bfa",
        "on-primary-fixed": "#003840",
        "on-tertiary": "#1b247f",
        "on-primary-fixed-variant": "#005762",
        "secondary-fixed-dim": "#efc900",
        "error-dim": "#d7383b",
        "surface-container-high": "#20201f",
        "on-primary-container": "#004d57",
        "inverse-surface": "#fcf9f8",
        "secondary-container": "#705d00",
        "outline-variant": "#484847",
        "primary": "#81ecff",
        "primary-container": "#00e3fd",
        "on-surface": "#ffffff",
        "on-primary": "#005762",
        "on-error": "#490006",
        "error": "#ff716c",
        "secondary-fixed": "#ffd709",
        "surface-variant": "#262626",
        "secondary-dim": "#efc900",
        "on-tertiary-container": "#0b1574",
        "on-surface-variant": "#adaaaa",
        "outline": "#767575",
        "surface-tint": "#81ecff",
        "on-tertiary-fixed-variant": "#252e88",
        "on-error-container": "#ffa8a3",
        "surface-container": "#1a1a1a",
        "on-tertiary-fixed": "#00055d",
        "on-secondary-fixed": "#453900",
        "surface": "#0e0e0e",
        "background": "#0e0e0e",
        "tertiary-container": "#929bfa"
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      "fontFamily": {
        "headline": ["Space Grotesk"],
        "body": ["Manrope"],
        "label": ["Manrope"]
      }
    },
  },
  plugins: [],
}
