export enum BuildingTypes {
  CAPITOL = 'CAPITOL',
  CAPITAL = 'CAPITAL',
  FARM = 'FARM',
  BARRACKS = 'BARRACKS',
  FORT = 'FORT',
  MARKET = 'MARKET',
  LIBRARY = 'LIBRARY',
  MINE = 'MINE',
  FORESTRY = 'FORESTRY',
  GARDEN = 'GARDEN',
  BAZAAR = 'BAZAAR',
  ARMORY = 'ARMORY',
}
